version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password_root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - default
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    networks:
      - default
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
  backend:
    image: maven:3-openjdk-17
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes: 
      - .:/app
    command: bash -c "cd app/projBackend/; mvn spring-boot:run"
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - default
  frontend:
    build: ./projFrontend
    depends_on:
      - backend
    volumes:
      - ./projFrontend/src:/projFrontend/src
      - /project/node_modules
    ports:
      - 5173:5173
    networks:
      - default
  
volumes:
  my-db:
  
networks:
  default:
    driver: bridge